/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Pizzeria.java
 *
 * Created on Jan 1, 2022, 6:29:39 PM
 */

package foodordering;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author zedso
 */
public class Pizzeria extends javax.swing.JFrame {

    double Price_Fries = 150;
    double Price_Soup = 320;
    double Price_Bisque = 200;
    double Price_Grill = 240;
    double Price_Burata = 150;
    double Price_Nicoise = 220;
    double Price_Josper = 190;
    double Price_Pepper = 300;
    double Price_Napolitana = 350;
    double Price_Margarita = 250;
    double Price_Creamy = 90;
    double Price_Mayo = 40;
    double Price_Cola = 100;
    double Price_Pepsi = 100;
    double Price_Fanta = 100;
    double Price_Orange = 150;
    double Tax_Rate = 30;

    double iTax,iTotal,iSubTotal,iChange,iCost;

    double[] itemcost = new double[18];



    /** Creates new form Pizzeria */
    public Pizzeria() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        Soup = new javax.swing.JTextField();
        Bisque = new javax.swing.JTextField();
        ChkSoup = new javax.swing.JCheckBox();
        ChkBisque = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        ChkFries = new javax.swing.JCheckBox();
        ChkCreamy = new javax.swing.JCheckBox();
        ChkMayo = new javax.swing.JCheckBox();
        Fries = new javax.swing.JTextField();
        Creamy = new javax.swing.JTextField();
        Mayo = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        ChkGrill = new javax.swing.JCheckBox();
        ChkBurata = new javax.swing.JCheckBox();
        ChkNicoise = new javax.swing.JCheckBox();
        ChkJosper = new javax.swing.JCheckBox();
        Grill = new javax.swing.JTextField();
        Burata = new javax.swing.JTextField();
        Nicoise = new javax.swing.JTextField();
        Josper = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        ChkCola = new javax.swing.JCheckBox();
        ChkPepsi = new javax.swing.JCheckBox();
        ChkFanta = new javax.swing.JCheckBox();
        ChkOrange = new javax.swing.JCheckBox();
        Cola = new javax.swing.JTextField();
        Pepsi = new javax.swing.JTextField();
        Fanta = new javax.swing.JTextField();
        Orange = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        ChkPepper = new javax.swing.JCheckBox();
        ChkNapolitana = new javax.swing.JCheckBox();
        ChkMargarita = new javax.swing.JCheckBox();
        Pepper = new javax.swing.JTextField();
        Napolitana = new javax.swing.JTextField();
        Margarita = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        cmbPaymentMethod = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        Cash = new javax.swing.JTextField();
        bTotal = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jTax = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jlblSubTotal = new javax.swing.JTextField();
        LblTotal = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        Change = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0), 4));
        jPanel5.setForeground(new java.awt.Color(204, 102, 0));
        jPanel5.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jPanel5AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        Soup.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Soup.setText("0");
        Soup.setEnabled(false);
        Soup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoupActionPerformed(evt);
            }
        });
        Soup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SoupKeyTyped(evt);
            }
        });

        Bisque.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Bisque.setText("0");
        Bisque.setEnabled(false);
        Bisque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BisqueActionPerformed(evt);
            }
        });
        Bisque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BisqueKeyTyped(evt);
            }
        });

        ChkSoup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChkSoup.setText("Minestrone Soup - 320");
        ChkSoup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkSoupActionPerformed(evt);
            }
        });

        ChkBisque.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChkBisque.setText("Langoustine Bisque - 200");
        ChkBisque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkBisqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(ChkSoup)
                        .addGap(18, 18, 18))
                    .addComponent(ChkBisque))
                .addGap(85, 85, 85)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Bisque)
                    .addComponent(Soup, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChkSoup)
                    .addComponent(Soup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bisque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChkBisque))
                .addGap(24, 24, 24))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0), 4));

        ChkFries.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChkFries.setText("French Fries - 150");
        ChkFries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkFriesActionPerformed(evt);
            }
        });

        ChkCreamy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChkCreamy.setText("Creamy Spinach - 90");
        ChkCreamy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkCreamyActionPerformed(evt);
            }
        });

        ChkMayo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChkMayo.setText("Chilli Mayonnaise - 40");
        ChkMayo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkMayoActionPerformed(evt);
            }
        });

        Fries.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Fries.setText("0");
        Fries.setEnabled(false);
        Fries.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FriesKeyTyped(evt);
            }
        });

        Creamy.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Creamy.setText("0");
        Creamy.setEnabled(false);
        Creamy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreamyActionPerformed(evt);
            }
        });
        Creamy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CreamyKeyTyped(evt);
            }
        });

        Mayo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Mayo.setText("0");
        Mayo.setEnabled(false);
        Mayo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MayoActionPerformed(evt);
            }
        });
        Mayo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MayoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChkFries)
                            .addComponent(ChkCreamy))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Creamy)
                            .addComponent(Fries, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(ChkMayo)
                        .addGap(38, 38, 38)
                        .addComponent(Mayo, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChkFries)
                    .addComponent(Fries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChkCreamy)
                    .addComponent(Creamy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChkMayo)
                    .addComponent(Mayo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0), 4));

        ChkGrill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChkGrill.setText("Grilled Vegetable - 240");
        ChkGrill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkGrillActionPerformed(evt);
            }
        });

        ChkBurata.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChkBurata.setText("Burata Salad - 150");
        ChkBurata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkBurataActionPerformed(evt);
            }
        });

        ChkNicoise.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChkNicoise.setText("Nicoise Salad - 220");
        ChkNicoise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkNicoiseActionPerformed(evt);
            }
        });

        ChkJosper.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChkJosper.setText("Josper Salmon - 190");
        ChkJosper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkJosperActionPerformed(evt);
            }
        });

        Grill.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Grill.setText("0");
        Grill.setEnabled(false);
        Grill.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GrillKeyTyped(evt);
            }
        });

        Burata.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Burata.setText("0");
        Burata.setEnabled(false);
        Burata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BurataKeyTyped(evt);
            }
        });

        Nicoise.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nicoise.setText("0");
        Nicoise.setEnabled(false);
        Nicoise.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NicoiseKeyTyped(evt);
            }
        });

        Josper.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Josper.setText("0");
        Josper.setEnabled(false);
        Josper.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JosperKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChkJosper)
                    .addComponent(ChkNicoise)
                    .addComponent(ChkBurata)
                    .addComponent(ChkGrill))
                .addGap(55, 55, 55)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Grill, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(Burata, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(Nicoise, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(Josper, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                .addGap(196, 196, 196))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChkGrill)
                    .addComponent(Grill, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChkBurata)
                    .addComponent(Burata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChkNicoise)
                    .addComponent(Nicoise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChkJosper)
                    .addComponent(Josper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0), 4));

        ChkCola.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChkCola.setText("Coca Cola - 100");
        ChkCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkColaActionPerformed(evt);
            }
        });

        ChkPepsi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChkPepsi.setText("Pepsi - 100");
        ChkPepsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkPepsiActionPerformed(evt);
            }
        });

        ChkFanta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChkFanta.setText("Fanta - 100");
        ChkFanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkFantaActionPerformed(evt);
            }
        });

        ChkOrange.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChkOrange.setText("Orange Juice - 150");
        ChkOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkOrangeActionPerformed(evt);
            }
        });

        Cola.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cola.setText("0");
        Cola.setEnabled(false);
        Cola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColaActionPerformed(evt);
            }
        });
        Cola.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ColaKeyTyped(evt);
            }
        });

        Pepsi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Pepsi.setText("0");
        Pepsi.setEnabled(false);
        Pepsi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PepsiKeyTyped(evt);
            }
        });

        Fanta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Fanta.setText("0");
        Fanta.setEnabled(false);
        Fanta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FantaKeyTyped(evt);
            }
        });

        Orange.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Orange.setText("0");
        Orange.setEnabled(false);
        Orange.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                OrangeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChkOrange)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ChkPepsi)
                        .addComponent(ChkFanta))
                    .addComponent(ChkCola))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Orange, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(Fanta)
                    .addComponent(Cola)
                    .addComponent(Pepsi))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChkCola)
                    .addComponent(Cola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChkPepsi)
                    .addComponent(Pepsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChkFanta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChkOrange)
                    .addComponent(Orange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0), 4));

        ChkPepper.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChkPepper.setText("Pepperoni Pizza - 300");
        ChkPepper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkPepperActionPerformed(evt);
            }
        });

        ChkNapolitana.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChkNapolitana.setText("Napolitana Pizza - 350");
        ChkNapolitana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkNapolitanaActionPerformed(evt);
            }
        });

        ChkMargarita.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChkMargarita.setText("Margarita Pizza - 250");
        ChkMargarita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkMargaritaActionPerformed(evt);
            }
        });

        Pepper.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Pepper.setText("0");
        Pepper.setEnabled(false);
        Pepper.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PepperKeyTyped(evt);
            }
        });

        Napolitana.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Napolitana.setText("0");
        Napolitana.setEnabled(false);
        Napolitana.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NapolitanaKeyTyped(evt);
            }
        });

        Margarita.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Margarita.setText("0");
        Margarita.setEnabled(false);
        Margarita.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MargaritaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ChkMargarita)
                        .addComponent(ChkNapolitana))
                    .addComponent(ChkPepper))
                .addGap(53, 53, 53)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Margarita)
                    .addComponent(Napolitana)
                    .addComponent(Pepper, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                .addContainerGap(638, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pepper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChkPepper))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Napolitana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChkNapolitana, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Margarita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChkMargarita))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("Soups");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setText("Drinks");

        jLabel64.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel64.setText("Additions");

        jLabel66.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel66.setText("Pizza");

        jLabel67.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel67.setText("Salads");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0), 4));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel1.setText("Restaurant Speciality");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel34.setText("Please Select Your Order");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(478, 478, 478)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(456, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0), 4));

        cmbPaymentMethod.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmbPaymentMethod.setText("Payment Method");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "Credit Card" }));

        Cash.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cash.setText("0");

        bTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bTotal.setText("Total");
        bTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(cmbPaymentMethod))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Cash, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bTotal)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(cmbPaymentMethod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bTotal)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0), 4));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Tax");

        jTax.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setText("Subtotal");

        jlblSubTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        LblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LblTotal.setText("Total");

        jlblTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlblTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblTotalActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Change");

        Change.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel33)
                    .addComponent(LblTotal)
                    .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jlblSubTotal)
                    .addComponent(jTax, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Change, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Change, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(btnReset))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel66)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel67))
                                    .addGap(45, 45, 45)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel26)
                                        .addComponent(jLabel64)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel64))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel67)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel66)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SoupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoupActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_SoupActionPerformed

    private void jPanel5AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel5AncestorMoved
        // TODO add your handling code here:
}//GEN-LAST:event_jPanel5AncestorMoved

    private void ChkSoupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkSoupActionPerformed
if (ChkSoup.isSelected())
      {
          Soup.setEnabled(true);
          Soup.requestFocus();
      }
 else
      {
          Soup.setEnabled(false);
 }          // TODO add your handling code here:
    }//GEN-LAST:event_ChkSoupActionPerformed

    private void ColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColaActionPerformed

    private void jlblTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblTotalActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jlblTotalActionPerformed

    private void ChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_ChangeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTotalActionPerformed
   itemcost[0] = Double.parseDouble(Fries.getText()) * Price_Fries;
   itemcost[1] = Double.parseDouble(Soup.getText()) *    Price_Soup ;
   itemcost[2] = Double.parseDouble(Bisque.getText()) *  Price_Bisque;
   itemcost[3] = Double.parseDouble(Grill.getText()) *  Price_Grill ;
   itemcost[4] = Double.parseDouble(Burata.getText()) *  Price_Burata ;
   itemcost[5] = Double.parseDouble(Nicoise.getText()) *  Price_Nicoise ;
   itemcost[6] = Double.parseDouble(Josper.getText()) *  Price_Josper;
   itemcost[7] = Double.parseDouble(Pepper.getText()) *  Price_Pepper ;
   itemcost[8] = Double.parseDouble(Napolitana.getText()) *  Price_Napolitana;
   itemcost[9] = Double.parseDouble(Margarita.getText()) *  Price_Margarita ;
   itemcost[10] = Double.parseDouble(Creamy.getText()) *  Price_Creamy;
   itemcost[11] = Double.parseDouble(Mayo.getText()) *  Price_Mayo ;
   itemcost[12] = Double.parseDouble(Cola.getText()) *  Price_Cola ;
   itemcost[13] = Double.parseDouble(Pepsi.getText()) *  Price_Pepsi ;
   itemcost[14] = Double.parseDouble(Fanta.getText()) *  Price_Fanta;
   itemcost[15] = Double.parseDouble(Orange.getText()) *  Price_Orange;
   iChange = Double.parseDouble(Cash.getText());

  String PaymentMethod = (String)jComboBox1.getSelectedItem();
if (PaymentMethod == "Cash")
{
  iSubTotal = itemcost[0] + itemcost[1] + itemcost[2] + itemcost[3] +
          itemcost[4] + itemcost[5] + itemcost[6] + itemcost[7] +
          itemcost[8] + itemcost[9] + itemcost[10] + itemcost[11]+
          itemcost[12] + itemcost[13] + itemcost[14] + itemcost[15];
  iTax= (iSubTotal * Tax_Rate) / 100 ;

  if (iChange>=iSubTotal)
  {
      iTax = (iSubTotal * Tax_Rate)/100;

      String uTax = String.format("$%.2f", iTax );
      jTax.setText(uTax);

      String uSubTotal = String.format("$%.2f",iSubTotal);
      jlblSubTotal.setText(uSubTotal);

      String aTotal=String.format("$%.2f",iSubTotal + iTax);
      jlblTotal.setText(String.valueOf(aTotal));
      String uChange = String.format("$%.2f", iChange - iSubTotal - iTax);
      Change.setText(uChange);

        }
    else
    {
        JOptionPane.showMessageDialog(null,"Not Enough Amount of Money Entered. Please Try Again.", "Restaurant Speciality", JOptionPane.OK_OPTION);
 }
        }
else if (PaymentMethod == "Credit Card")
    {
        iSubTotal = itemcost[0] + itemcost[1] + itemcost[2] + itemcost[3] + itemcost[4]+ itemcost[5]
            + itemcost[6] + itemcost[7] + itemcost[8] + itemcost[9] + itemcost[10] + itemcost[11] + itemcost[12] + itemcost[13] + itemcost[14]+
            itemcost[15];

    iTax = ( iSubTotal * Tax_Rate)/100;

   String cTax = String.format("$%.2f", iTax);
    jTax.setText(cTax);

    String cSubTotal = String.format("$%.2f", iSubTotal);
    jlblSubTotal.setText(cSubTotal);

    double uTotal = new TotalClass().getTotal();

    String cTotal = String.format("$%.2f", iSubTotal + iTax);
    jlblTotal.setText(String.valueOf(cTotal));



    String cChange = String.format("$%.2f", iChange - iSubTotal - iTax);
 Change.setText(cChange);

 }




            // TODO add your handling code here:
    }//GEN-LAST:event_bTotalActionPerformed

    private void ChkFriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkFriesActionPerformed
if (ChkFries.isSelected())
      {
          Fries.setEnabled(true);
          Fries.requestFocus();

      }
 else
      {
          Fries.setEnabled(false);
        
 }        // TODO add your handling code here:
    }//GEN-LAST:event_ChkFriesActionPerformed

    private void ChkBisqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkBisqueActionPerformed
if (ChkBisque.isSelected())
      {
          Bisque.setEnabled(true);
          Bisque.requestFocus();
      }
 else
      {
          Bisque.setEnabled(false);
 }          // TODO add your handling code here:
    }//GEN-LAST:event_ChkBisqueActionPerformed

    private void ChkGrillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkGrillActionPerformed
if (ChkGrill.isSelected())
      {
          Grill.setEnabled(true);
          Grill.requestFocus();
      }
 else
      {
          Grill.setEnabled(false);
 }          // TODO add your handling code here:
    }//GEN-LAST:event_ChkGrillActionPerformed

    private void ChkBurataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkBurataActionPerformed
if (ChkBurata.isSelected())
      {
          Burata.setEnabled(true);
          Burata.requestFocus();
      }
 else
      {
          Burata.setEnabled(false);
 }          // TODO add your handling code here:
    }//GEN-LAST:event_ChkBurataActionPerformed

    private void ChkNicoiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkNicoiseActionPerformed
if (ChkNicoise.isSelected())
      {
          Nicoise.setEnabled(true);
          Nicoise.requestFocus();
      }
 else
      {
          Nicoise.setEnabled(false);
 }          // TODO add your handling code here:
    }//GEN-LAST:event_ChkNicoiseActionPerformed

    private void ChkJosperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkJosperActionPerformed
     if (ChkJosper.isSelected())
      {
          Josper.setEnabled(true);
          Josper.requestFocus();
      }
 else
      {
          Josper.setEnabled(false);
 }   // TODO add your handling code here:
    }//GEN-LAST:event_ChkJosperActionPerformed

    private void ChkPepperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkPepperActionPerformed
if (ChkPepper.isSelected())
      {
          Pepper.setEnabled(true);
          Pepper.requestFocus();
      }
 else
      {
          Pepper.setEnabled(false);
 }        // TODO add your handling code here:
    }//GEN-LAST:event_ChkPepperActionPerformed

    private void ChkNapolitanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkNapolitanaActionPerformed
if (ChkNapolitana.isSelected())
      {
          Napolitana.setEnabled(true);
          Napolitana.requestFocus();
      }
 else
      {
          Napolitana.setEnabled(false);
 }        // TODO add your handling code here:
    }//GEN-LAST:event_ChkNapolitanaActionPerformed

    private void ChkMargaritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkMargaritaActionPerformed
if (ChkMargarita.isSelected())
      {
          Margarita.setEnabled(true);
          Margarita.requestFocus();
      }
 else
      {
          Margarita.setEnabled(false);
 }        // TODO add your handling code here:
    }//GEN-LAST:event_ChkMargaritaActionPerformed

    private void ChkCreamyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkCreamyActionPerformed
if (ChkCreamy.isSelected())
      {
          Creamy.setEnabled(true);
          Creamy.requestFocus();
      }
 else
      {
          Creamy.setEnabled(false);
 }        // TODO add your handling code here:
    }//GEN-LAST:event_ChkCreamyActionPerformed

    private void ChkMayoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkMayoActionPerformed
if (ChkMayo.isSelected())
      {
          Mayo.setEnabled(true);
          Mayo.requestFocus();
      }
 else
      {
          Mayo.setEnabled(false);
 }        // TODO add your handling code here:
    }//GEN-LAST:event_ChkMayoActionPerformed

    private void ChkColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkColaActionPerformed
if (ChkCola.isSelected())
      {
          Cola.setEnabled(true);
          Cola.requestFocus();
      }
 else
      {
          Cola.setEnabled(false);
 }        // TODO add your handling code here:
    }//GEN-LAST:event_ChkColaActionPerformed

    private void ChkPepsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkPepsiActionPerformed
if (ChkPepsi.isSelected())
      {
          Pepsi.setEnabled(true);
          Pepsi.requestFocus();
      }
 else
      {
          Pepsi.setEnabled(false);
 }        // TODO add your handling code here:
    }//GEN-LAST:event_ChkPepsiActionPerformed

    private void ChkFantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkFantaActionPerformed
if (ChkFanta.isSelected())
      {
          Fanta.setEnabled(true);
          Fanta.requestFocus();
      }
 else
      {
          Fanta.setEnabled(false);
 }        // TODO add your handling code here:
    }//GEN-LAST:event_ChkFantaActionPerformed

    private void ChkOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkOrangeActionPerformed
    if (ChkOrange.isSelected())
      {
          Orange.setEnabled(true);
          Orange.requestFocus();
      }
 else
      {
          Orange.setEnabled(false);
 }    // TODO add your handling code here:
    }//GEN-LAST:event_ChkOrangeActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
Cash.setText(null);
Change.setText(null);
jTax.setText(null);
jlblSubTotal.setText(null);
jlblTotal.setText(null);

                //========================
Cola.setEnabled(false);
        Fries.setEnabled(false);
        Fanta.setEnabled(false);
        Pepsi.setEnabled(false);
                Burata.setEnabled(false);
                Nicoise.setEnabled(false);
                Napolitana.setEnabled(false);
                Margarita.setEnabled(false);
                Creamy.setEnabled(false);
                Mayo.setEnabled(false);
                Grill.setEnabled(false);
                Josper.setEnabled(false);
                Pepper.setEnabled(false);
                Soup.setEnabled(false);
                Bisque.setEnabled(false);
                Orange.setEnabled(false);

                //=======================
                Cola.setText(null);
        Fries.setText(null);
        Fanta.setText(null);
        Pepsi.setText(null);
                Burata.setText(null);
                Nicoise.setText(null);
                Napolitana.setText(null);
                Margarita.setText(null);
                Mayo.setText(null);
                Creamy.setText(null);
                Josper.setText(null);
                Pepper.setText(null);
                Soup.setText(null);
                Bisque.setText(null);
                Grill.setText(null);
                Orange.setText(null);

                //=======================
         ChkSoup.setSelected(false);
         ChkBisque.setSelected(false);
         ChkGrill.setSelected(false);
         ChkFries.setSelected(false);
         ChkCreamy.setSelected(false);
         ChkMayo.setSelected(false);
         ChkBurata.setSelected(false);
         ChkNicoise.setSelected(false);
         ChkJosper.setSelected(false);
         ChkCola.setSelected(false);
         ChkPepsi.setSelected(false);
         ChkFanta.setSelected(false);
         ChkOrange.setSelected(false);
         ChkPepper.setSelected(false);
         ChkNapolitana.setSelected(false);
         ChkMargarita.setSelected(false);

                // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void SoupKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SoupKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_SoupKeyTyped

    private void BisqueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BisqueKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_BisqueKeyTyped

    private void GrillKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GrillKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_GrillKeyTyped

    private void BurataKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BurataKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_BurataKeyTyped

    private void NicoiseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NicoiseKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_NicoiseKeyTyped

    private void JosperKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JosperKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_JosperKeyTyped

    private void PepperKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PepperKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_PepperKeyTyped

    private void NapolitanaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NapolitanaKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_NapolitanaKeyTyped

    private void MargaritaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MargaritaKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_MargaritaKeyTyped

    private void FriesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FriesKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_FriesKeyTyped

    private void CreamyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CreamyKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_CreamyKeyTyped

    private void MayoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MayoKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_MayoKeyTyped

    private void ColaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ColaKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_ColaKeyTyped

    private void PepsiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PepsiKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_PepsiKeyTyped

    private void FantaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FantaKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_FantaKeyTyped

    private void OrangeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OrangeKeyTyped
char Number = evt.getKeyChar();
    if (!(Character.isDigit(Number))
        || (Number == KeyEvent.VK_BACK_SPACE)
                || (Number ==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_OrangeKeyTyped

    private void BisqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BisqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BisqueActionPerformed

    private void CreamyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreamyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreamyActionPerformed

    private void MayoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MayoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MayoActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizzeria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bisque;
    private javax.swing.JTextField Burata;
    private javax.swing.JTextField Cash;
    private javax.swing.JTextField Change;
    private javax.swing.JCheckBox ChkBisque;
    private javax.swing.JCheckBox ChkBurata;
    private javax.swing.JCheckBox ChkCola;
    private javax.swing.JCheckBox ChkCreamy;
    private javax.swing.JCheckBox ChkFanta;
    private javax.swing.JCheckBox ChkFries;
    private javax.swing.JCheckBox ChkGrill;
    private javax.swing.JCheckBox ChkJosper;
    private javax.swing.JCheckBox ChkMargarita;
    private javax.swing.JCheckBox ChkMayo;
    private javax.swing.JCheckBox ChkNapolitana;
    private javax.swing.JCheckBox ChkNicoise;
    private javax.swing.JCheckBox ChkOrange;
    private javax.swing.JCheckBox ChkPepper;
    private javax.swing.JCheckBox ChkPepsi;
    private javax.swing.JCheckBox ChkSoup;
    private javax.swing.JTextField Cola;
    private javax.swing.JTextField Creamy;
    private javax.swing.JTextField Fanta;
    private javax.swing.JTextField Fries;
    private javax.swing.JTextField Grill;
    private javax.swing.JTextField Josper;
    private javax.swing.JLabel LblTotal;
    private javax.swing.JTextField Margarita;
    private javax.swing.JTextField Mayo;
    private javax.swing.JTextField Napolitana;
    private javax.swing.JTextField Nicoise;
    private javax.swing.JTextField Orange;
    private javax.swing.JTextField Pepper;
    private javax.swing.JTextField Pepsi;
    private javax.swing.JTextField Soup;
    private javax.swing.JButton bTotal;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel cmbPaymentMethod;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTax;
    private javax.swing.JTextField jlblSubTotal;
    private javax.swing.JTextField jlblTotal;
    // End of variables declaration//GEN-END:variables

}
